### ISSUE TITLE
global address required 

### ISSUE THREAD

**Issue by Vutsuak16** [minallaad/SER517-Capstone---Project-10#78]
![Screen Shot 2019-04-23 at 10 30 16 AM](https://user-images.githubusercontent.com/10365536/56602725-004b5880-65b3-11e9-88c6-bdcc1190bf79.png)

one can use os.getcwd() module to fix this issue
want me to raise a PR for this?

**Comment by sahebjohar92** [comment]
We don't need this, after we integrate with codeblocks, it will provide the file path, this is just a temporary thing

**Comment by Vutsuak16** [comment]
perfect I am closing this issue?
